In [1]:
import pandas as pd 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [19]:
df = pd.read_csv("Student_Performance.csv")

In [20]:
df = df.rename(columns = {"Hours Studied":"hours","Previous Scores":"pr scores","Sleep Hours":"shours","Sample Question Papers Practiced":"q papers","Extracurricular Activities":"extra activities"})

In [21]:
df[["extra activities"]] = df[["extra activities"]].replace("Yes",1).replace("No",0)

C:\Users\zainw\AppData\Local\Temp\ipykernel_9892\1412459943.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[["extra activities"]] = df[["extra activities"]].replace("Yes",1).replace("No",0)

In [22]:
y = df[["Performance Index"]]

In [23]:
df

      hours  pr scores  extra activities  shours  q papers  Performance Index
0         7         99                 1       9         1               91.0
1         4         82                 0       4         2               65.0
2         8         51                 1       7         2               45.0
3         5         52                 1       5         2               36.0
4         7         75                 0       8         5               66.0
...     ...        ...               ...     ...       ...                ...
9995      1         49                 1       4         2               23.0
9996      7         64                 1       8         5               58.0
9997      6         83                 1       8         5               74.0
9998      9         97                 1       7         0               95.0
9999      7         74                 0       8         1               64.0

[10000 rows x 6 columns]

In [24]:
y

      Performance Index
0                  91.0
1                  65.0
2                  45.0
3                  36.0
4                  66.0
...                 ...
9995               23.0
9996               58.0
9997               74.0
9998               95.0
9999               64.0

[10000 rows x 1 columns]

In [25]:
x = df.drop("Performance Index",axis = 1)

In [26]:
x

      hours  pr scores  extra activities  shours  q papers
0         7         99                 1       9         1
1         4         82                 0       4         2
2         8         51                 1       7         2
3         5         52                 1       5         2
4         7         75                 0       8         5
...     ...        ...               ...     ...       ...
9995      1         49                 1       4         2
9996      7         64                 1       8         5
9997      6         83                 1       8         5
9998      9         97                 1       7         0
9999      7         74                 0       8         1

[10000 rows x 5 columns]

In [27]:
y

      Performance Index
0                  91.0
1                  65.0
2                  45.0
3                  36.0
4                  66.0
...                 ...
9995               23.0
9996               58.0
9997               74.0
9998               95.0
9999               64.0

[10000 rows x 1 columns]

In [28]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.2,random_state = 101)

In [29]:
X_train

      hours  pr scores  extra activities  shours  q papers
6861      3         67                 1       5         1
9881      1         78                 0       8         8
4536      9         98                 0       7         6
8430      5         65                 0       8         4
6765      9         44                 1       4         8
...     ...        ...               ...     ...       ...
599       9         53                 0       4         2
5695      4         92                 1       8         2
8006      9         40                 1       9         5
1361      7         51                 0       8         2
1547      5         43                 0       7         9

[8000 rows x 5 columns]

In [30]:
reg = LinearRegression()

In [31]:
reg.fit(X_train,Y_train)

LinearRegression()

In [32]:
X_test

      hours  pr scores  extra activities  shours  q papers
6676      7         55                 0       4         3
6421      9         98                 1       7         4
9834      1         57                 1       6         1
8492      3         71                 0       5         3
9982      8         51                 0       5         1
...     ...        ...               ...     ...       ...
4441      1         65                 1       6         7
4166      1         65                 1       4         6
2567      4         62                 0       9         6
8527      9         64                 0       4         5
406       1         42                 1       8         4

[2000 rows x 5 columns]

In [42]:
reg.predict([[7,55,0,4,3]])[0][0] - 1

C:\Users\zainw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

np.float64(43.388914219062464)

In [36]:
Y_test

      Performance Index
6676               43.0
6421               95.0
9834               29.0
8492               48.0
9982               44.0
...                 ...
4441               38.0
4166               42.0
2567               46.0
8527               61.0
406                17.0

[2000 rows x 1 columns]